# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5d8ac8f73336bb5515cd496217989a57594bc7b822f55bcbb7eb2f897f1ced3cc3a3a4afe1bca559c358b25caa58a53bb0f31c0f3434680001b3cca66ed07a4

test:
  secret_key_base: bb403a492c4f83ef21c63149ca7d5209f887fac8bf6f53b40a4f7e64a46205610455db693af3700560741dec53feba9d6b532192f3be5218819c24e7e8438f63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
